### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by thomaswilliamsastro** [Vb2341/One-Pass-Fitting#1]
Just starting to dig into this to see if PSF photometry can help the astrometry issues we still have outstanding in the PHANGS-JWST data. I've got things mostly working, but just to flag up that Iterable has been removed now from collections as of py3.10. It still exists in collections.abc, so currently I have to do this:

```
import collections.abc
collections.Iterable = collections.abc.Iterable
collections.Mapping = collections.abc.Mapping
collections.MutableSet = collections.abc.MutableSet
collections.MutableMapping = collections.abc.MutableMapping
```

**Comment by Vb2341** [comment]
Whoops, I meant to fix that a couple weeks ago, there's now a try/except to hopefully work around that in the code.  As you might have guess, I was working in a 3.9 environment, but hopefully this is now fixed.
